#!/bin/bash
clear
echo "Running Pair Approach" 
hadoop fs -rm -r relativefrequency/input
hadoop fs -rm -r relativefrequency/output/pair
hadoop fs -mkdir -p relativefrequency
hadoop fs -put input relativefrequency
cd target
hadoop jar PairApproach-1.0.jar mum.cs.edu.RelativeFrequency relativefrequency/input relativefrequency/output/pair
echo "Pair Approach - Output"
hadoop fs -cat relativefrequency/output/pair/*
